POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsImV4cCI6MTczOTA0MTgxNiwidXNlcklkIjoyfQ.UChDD7JcZLkuKqQ10qwSAaD4VNvQ4u70kUJ7hYxiGGE